# Generated by Django 3.0.8 on 2021-03-14 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0002_auto_20210314_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('rut', models.CharField(db_index=True, max_length=12)),
                ('customatizacion', models.CharField(db_index=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='menu.Option')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['id'], name='order_order_id_11b17b_idx'),
        ),
    ]
